version: '3'

services:
  comida-boteco-proxy:
    container_name: comida-boteco-proxy
    image: nginx:1.20
    restart: always

    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app/build:/var/www/html
      - ./nginx/access.log:/var/log/nginx_access.log
      - ./nginx/error.log:/var/log/nginx_error.log
      - ${NGINX_SSL_FULLCHAIN}:/home/fullchain.pem
      - ${NGINX_SSL_PRIVKEY}:/home/privkey.pem
    depends_on:
      - comida-boteco-api

  comida-boteco-api:
    container_name: comida-boteco-api
    image: python:3.9
    build: .
    restart: always
    volumes:
      - ./api:/app

    command: bash -c "pip install --upgrade pip && python -m pip install gunicorn && python manage.py makemigrations && python manage.py migrate && gunicorn config.wsgi:application -b :8000"

