# Generated by Django 4.2.11 on 2024-03-29 23:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'bar',
            },
        ),
        migrations.CreateModel(
            name='Votos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cpf', models.CharField(max_length=11)),
                ('apresentacao_prato', models.IntegerField()),
                ('aroma_prato', models.IntegerField()),
                ('sabor_prato', models.IntegerField()),
                ('tempo_espera', models.IntegerField()),
                ('bebida', models.IntegerField()),
                ('higiene_local', models.IntegerField()),
                ('ambiente', models.IntegerField()),
                ('bar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='votos.bar')),
            ],
            options={
                'db_table': 'votos',
            },
        ),
    ]
