# Generated by Django 4.2.11 on 2024-03-30 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='url_bar',
            field=models.CharField(default='', help_text='Digite somente o caminho, ex /trauko, /toro', max_length=50, verbose_name='URL do bar'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='votos',
            name='ambiente',
            field=models.IntegerField(help_text='nota de 1 a 10', verbose_name='Hambiente'),
        ),
        migrations.AlterField(
            model_name='votos',
            name='apresentacao_prato',
            field=models.IntegerField(help_text='nota de 1 a 10', verbose_name='Apresentação do Prato'),
        ),
        migrations.AlterField(
            model_name='votos',
            name='aroma_prato',
            field=models.IntegerField(help_text='nota de 1 a 10', verbose_name='Aroma do Prato'),
        ),
        migrations.AlterField(
            model_name='votos',
            name='bebida',
            field=models.IntegerField(help_text='nota de 1 a 10', verbose_name='Bebida'),
        ),
        migrations.AlterField(
            model_name='votos',
            name='cpf',
            field=models.CharField(help_text='Somente Dígitos', max_length=11, verbose_name='Seu CPF'),
        ),
        migrations.AlterField(
            model_name='votos',
            name='higiene_local',
            field=models.IntegerField(help_text='nota de 1 a 10', verbose_name='Higiene do local'),
        ),
        migrations.AlterField(
            model_name='votos',
            name='sabor_prato',
            field=models.IntegerField(help_text='nota de 1 a 10', verbose_name='Sabor do Prato'),
        ),
        migrations.AlterField(
            model_name='votos',
            name='tempo_espera',
            field=models.IntegerField(help_text='nota de 1 a 10', verbose_name='Aroma do Prato'),
        ),
    ]
