# Generated by Django 4.2.11 on 2024-03-30 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votos', '0002_bar_url_bar_alter_votos_ambiente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bar',
            name='nome',
            field=models.CharField(help_text='Máximo 50 caractares', max_length=20, verbose_name='Nome do Bar'),
        ),
        migrations.AlterField(
            model_name='votos',
            name='tempo_espera',
            field=models.IntegerField(help_text='nota de 1 a 10', verbose_name='Tempo de espera'),
        ),
    ]
