# Generated by Django 4.2.11 on 2024-04-05 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votos', '0003_alter_bar_nome_alter_votos_tempo_espera'),
    ]

    operations = [
        migrations.AddField(
            model_name='votos',
            name='atendimento',
            field=models.IntegerField(default=0, help_text='nota de 1 a 10', verbose_name='Aroma do Prato'),
            preserve_default=False,
        ),
    ]
