# Generated by Django 4.2.11 on 2024-04-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votos', '0004_votos_atendimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bar',
            name='nome',
            field=models.CharField(help_text='Máximo 50 caractares', max_length=100, verbose_name='Nome do Bar'),
        ),
        migrations.AlterField(
            model_name='bar',
            name='url_bar',
            field=models.CharField(help_text='digite o texto do código QR, ex BARDOTRAUKO, PUBPIZZARIADORICARDO', max_length=50, verbose_name='Código QR do bar'),
        ),
    ]
